Add tests for WaveletDenoize class
genome-rcast/karkinos pull request #13
Opened 2020-08-18 07:27 UTC by xckitahara

Add tests for WaveletDenoize class.

2020-08-18 09:16 UTC, alumi requested changes
- Separate testing logic and data by making a good use of JUnit API such as `@MethodSource` to highlight inputs and outputs.
- Use some linter to check your code before submitting PRs. I recommend the code inspection of IDEA if you don't have a particular preference.
- Leverage features like stream API to tidy up building objects.
- There're so many codes for reflection. Maybe a library like Manifold's `@Jailbreak` will help to keep the codes clean. (I'm not familiar with it)

2020-08-18 09:16 UTC, alumi commented on src/test/java/jp/ac/utokyo/rcast/karkinos/wavelet/WaveletDenoizeTest.java
> +            list.add(ci6);
Intervals of both "chr1" and "chr2" are added to a single list here. Is this correct in a real environment?

2020-08-24 04:16 UTC, xckitahara commented on src/test/java/jp/ac/utokyo/rcast/karkinos/wavelet/WaveletDenoizeTest.java
> +            list.add(ci6);
We don't refer to chr1 information in the process, so it doesn't affect us, but it's different from the actual environment, so we'll fix it.

2020-08-24 04:19 UTC, xckitahara commented
The whole thing has been revised in response to comments.

2020-08-24 09:30 UTC, alumi requested changes
I'm in the middle of a review, but let me make a few comments.

2020-08-24 09:30 UTC, alumi commented on src/test/java/jp/ac/utokyo/rcast/karkinos/wavelet/WaveletDenoizeTest.java
> +                cnt = cnt + 1;
```suggestion
                cnt++;
```

2020-08-24 09:30 UTC, alumi commented on src/test/java/jp/ac/utokyo/rcast/karkinos/wavelet/WaveletDenoizeTest.java
> +                assertThat(wif.getCN(), is(expCN[cnt]));
Why do you use different assertions (`assertEquals(double, double, double)` and `assertThat<Double>(Double, Matcher<Double>)`) here? I think `assertEquals` is more suitable for the second one.

2020-08-24 09:30 UTC, alumi commented on src/test/java/jp/ac/utokyo/rcast/karkinos/wavelet/WaveletDenoizeTest.java
> +    void calcTest(DataSet dataset, double expLoh, double[] expDeNoiseValue, double[] expCN) throws IOException {
Wrap lines at 80 characters
```suggestion
    void calcTest(DataSet dataset,
                  double expLoh,
                  double[] expDeNoiseValue,
                  double[] expCN) throws IOException {
```

2020-08-24 09:30 UTC, alumi commented on src/test/java/jp/ac/utokyo/rcast/karkinos/wavelet/WaveletDenoizeTest.java
> +        @Jailbreak DataSet dataset2 = new DataSet(dummyIndex);
We don't need this map, right?
```suggestion
        @Jailbreak DataSet dataset1 = new DataSet(null);
        @Jailbreak DataSet dataset2 = new DataSet(null);
```

2020-08-24 09:30 UTC, alumi commented on src/test/java/jp/ac/utokyo/rcast/karkinos/wavelet/WaveletDenoizeTest.java
> +    }
I felt like a little bit hard to read the values tested so I want the data of interest to be completely separated from codes.
Something like the following will help to make it easy to add more test data.

```suggestion
    static Stream<Arguments> calcParameters() {
        return Stream.of(
            // normalCounts, tnRatios, expLoh, expDeNoiseValues, expCNs
            Arguments.of(
                new int[][] {{1, 2, 3}, {4, 5, 6}},
                new double[][] {{0.1, 0.2, 0.3}, {1.1, 1.2, 1.3}},
                0.51,
                new double[][] {{0.21765567128029326, 0.21765567128029326,
                    0.21765567128029326}, {1.206723294623865,
                    1.206723294623865, 1.206723294623865}},
                new double[][] {{0.5, 0.5, 0.5}, {1.0, 1.0, 1.0}}),
            Arguments.of(
                new int[][]{{1, 2, 3, 4, 5, 6}},
                new double[][] {{2.1, 2.2, 2.3, 2.1, 2.2, 2.3}},
                0.90,
                new double[][] {{2.2109080498231073, 2.2109080498231073,
                    2.2109080498231073, 2.2109080498231073,
                    2.2109080498231073, 2.2109080498231073}},
                new double[][] {{7.0, 7.0, 7.0, 7.0, 7.0, 7.0}}));
    }

    @ParameterizedTest
    @MethodSource("calcParameters")
    void calcTest(final int[][] normalCounts,
                  final double [][] tnRatios,
                  final double expLoh,
                  final double[][] expDeNoiseValues,
                  final double[][] expCNs) throws IOException {
        @Jailbreak final DataSet dataset = new DataSet(null);
        dataset.capintervalinit = true;
        dataset.capinterval = IntStream.range(0, tnRatios.length).mapToObj(i->
            IntStream.range(0, tnRatios[i].length).mapToObj(j->{
                final CapInterval ci = new CapInterval("chr"+i, j, j+1, true);
                ci.setCNVInfo(new CNVInfo(normalCounts[i][j],
                    0.0, 0.0, 1, 0.0, 0.0, tnRatios[i][j]));
                return (WaveletIF)ci;})
                .collect(Collectors.toList()))
            .collect(Collectors.toList());
        final double baselineLOHEstimate = WaveletDenoize.calc(dataset);

        final double delta = 1e-7;
        assertEquals(expLoh, baselineLOHEstimate, delta);
        final List<List<WaveletIF>> capInterval = dataset.getCapInterval();
        int chr = 0;
        for (final List<WaveletIF> l : capInterval) {
            assertArrayEquals(expDeNoiseValues[chr],
                l.stream().mapToDouble(WaveletIF::getDenioseValue).toArray());
            assertArrayEquals(expCNs[chr],
                l.stream().mapToDouble(WaveletIF::getCN).toArray());
            chr++;
        }
    }
```

2020-08-24 09:30 UTC, alumi commented on src/test/java/jp/ac/utokyo/rcast/karkinos/wavelet/WaveletDenoizeTest.java
> +        IntStream.range(1024, 4096 / 4)
??

2020-08-24 09:30 UTC, alumi commented on src/test/java/jp/ac/utokyo/rcast/karkinos/wavelet/WaveletDenoizeTest.java
> +                .forEach(i -> IntStream.range(0, 2)
Perfer `toArray` and `flatMap` over `forEach` if possible

2020-08-25 00:47 UTC, xckitahara commented
It's committed with GPG, but it may have disappeared when I rebased it.

2020-08-25 02:38 UTC, xckitahara commented on src/test/java/jp/ac/utokyo/rcast/karkinos/wavelet/WaveletDenoizeTest.java
> +                assertThat(wif.getCN(), is(expCN[cnt]));
I thought it would be better to use assertThat.
I tried to use assertEquals when there is an error.
Unified into assertEquals.

2020-08-26 06:44 UTC, alumi requested changes

2020-08-26 06:44 UTC, alumi commented on src/test/java/jp/ac/utokyo/rcast/karkinos/wavelet/WaveletDenoizeTest.java
> +        List<double[]> l1 = new ArrayList<>(Arrays.asList(
```suggestion
        List<double[]> l1 = Arrays.asList(
```

2020-08-26 06:44 UTC, alumi commented on src/test/java/jp/ac/utokyo/rcast/karkinos/wavelet/WaveletDenoizeTest.java
> +                .forEach(i -> deNoiseValue2[0][i] = 0.24);
```suggestion
        double[][] deNoiseValue1 = new double[1][100];
        Arrays.fill(deNoiseValue1[0], 0, 96, 0.7);
        Arrays.fill(deNoiseValue1[0], 96, 100, 0.24);

        double[][] deNoiseValue2 = new double[][]{deNoiseValue1[0].clone()};
        deNoiseValue2[0][96] = 0.7;
```

2020-08-26 06:44 UTC, alumi commented on build.gradle
> +    implementation 'systems.manifold:manifold-ext-rt:2020.1.24'
We need to exclude a runtime dependency to manifold in order to build and run uberjar without it.
Check `./gradlew uberjar && ! jar tf build/libs/karkinos-standalone-2.0.5-SNAPSHOT.jar | grep manifold; java -jar build/libs/karkinos-standalone-2.0.5-SNAPSHOT.jar analysis`

```suggestion
    testImplementation 'systems.manifold:manifold-ext-rt:2020.1.24'
```

2020-08-26 06:44 UTC, alumi commented on build.gradle
> +    tasks.withType(JavaCompile) {
```suggestion
    compileTestJava {
```

2020-08-26 06:44 UTC, alumi commented on build.gradle
> +    tasks.withType(JavaCompile) {
```suggestion
    compileTestJava {
```

2020-09-04 01:39 UTC, alumi approved these changes, later dismissed
LGTM 👍 
Would you squash the commits into one, sign it with GPG, and push it with `--force-with-lease`?

2020-09-04 01:59 UTC, xckitahara commented
Thanks for the review.
I squashed it and pushed it.

2020-09-04 02:49 UTC, alumi approved these changes

2020-09-04 02:49 UTC, merged